In [ ]:
class human :
  def __init__(self) -> None:
      pass
  def hello(self) :
    print("hi")



In [ ]:
m = human()

In [ ]:
m.hello()

hi


In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8])
x+y
v = list([1,2,3])
w = [4,5]
v+w

[1, 2, 3, 4, 5]

In [ ]:
X = np.array([[51, 55], [14, 19], [0, 4]])
X[1,1]
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [ ]:
X = X.flatten()
X[[0,2,4]]

array([51, 14,  0])

In [ ]:
import time
time.clock

<function time.clock>

In [ ]:
Y=[1,5,10,40,3,23,52]

In [ ]:
A=np.arange(10)
A.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
B=np.arange(18).reshape(2,3,1,-1)
B
C=B.reshape(2,3,-1)
print(B,'\n\n',C)

[[[[ 0  1  2]]

  [[ 3  4  5]]

  [[ 6  7  8]]]


 [[[ 9 10 11]]

  [[12 13 14]]

  [[15 16 17]]]] 

 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [ ]:
arr = np.arange(24).reshape(2, 3, 2,-1)
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [ ]:
arr.sum(axis=1)

array([[[12, 15],
        [18, 21]],

       [[48, 51],
        [54, 57]]])

In [11]:
import matplotlib.pyplot as plt
from matplotlib.image import imread
from google.colab import files
uploaded = files.upload()

KeyboardInterrupt: ignored

In [ ]:
img = imread('course.webp') # 이미지 읽어오기(적절한 경로를 설정하세요!)

plt.imshow(img)
plt.show()

In [1]:
from matplotlib import font_manager

In [3]:
fonts = font_manager.findSystemFonts()
fonts

['/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationSansNarrow-BoldItalic.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Italic.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf',
 '/usr/share/fonts/truetype/humor-sans/Humor-Sans.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationMono-Italic.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationMono-BoldItalic.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf',
 '/usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf',
 '/usr/share/fonts/truetype/liberation/L

In [6]:
print([font for font in fonts if 'malgun' in font])

[]


In [12]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 45 not upgraded.
Need to get 9,604 kB of archives.
After this operation, 29.5 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 fonts-nanum all 20170925-1 [9,604 kB]
Fetched 9,604 kB in 0s (24.4 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype

In [2]:
from matplotlib import rc
import matplotlib.pyplot as plt

plt.rc('font', family='NanumBarunGothic')

fig, ax = plt.subplots()
ax.plot([1,2,3],[3,2,1], label = '한글')
ax.legend()
